# host_vars/pumba
# vi: ft=yaml
---

####################################################

samba_shares:
  - name: forusera
  - name: foruserb
  - name: readenwrite
  - name: publiek
    public: yes

samba_test_publiek:
  - share: publiek
    denied_write:
      - "usera"
      - "userb"
      - "admin"

samba_test:
  - share: forusera
    allowed_read:
      - "usera"
      - "admin"
    denied_read:
      - "userb"

    allowed_write:
      - "usera"
      - "admin"
    denied_write:
      - "userb"
#################################
  - share: foruserb
    allowed_read:
      - "userb"
      - "admin"
    denied_read:
      - "usera"

    allowed_write:
      - "userb"
      - "admin"
    denied_write:
      - "usera"
#################################
  - share: readenwrite
    allowed_read:
      - "usera"
      - "admin"
      - "userb"
    denied_read:
      - "publiek_user"

    allowed_write:
      - "usera"
      - "admin"
    denied_write:
      - "userb"
#################################

samba_users:
  - name: usera
  - name: userb
  - name: admin

samba_url: "filesrv.linuxlab.net"
samba_netbios_name: FILESRV
samba_workgroup: LINUXLAB
samba_ip: "192.168.2.2"

######################################################################################""
bind_zone_name: "linuxlab.net"

bind_ip_addr: "192.168.2.2"

bind_recursion: "yes"

bind_zone_name_servers:
  - "pu001"

bind_zone_mail_servers:
  - name: "mail"
    preference: "10"

bind_zone_hosts:
  - name: pu001
    ip: 192.168.2.2
    aliases:
      - ns1
      - FILESRV
  - name: pu002
    ip: 192.168.2.3
    aliases:
      - ns2
  - name: pu010
    ip: 192.168.2.10
    aliases:
      - www
  - name: pu020
    ip: 192.168.2.20
    aliases:
      - mail
      - smtp
      - imap