# roles/common/main.yml
---
- name: Installeren van globale packages
  yum: pkg={{item}} state=installed
  with_items:
    - libselinux-python
    - libsemanage-python
    - pcre-tools
  tags: common

- name: Firewall aanzetten
  service: name=firewalld state=running enabled=true
  tags: common

- name: Hostname in hosts file zetten
  lineinfile:
    dest=/etc/hosts
    state=present
    line="{{ ansible_all_ipv4_addresses|last }} {{ ansible_hostname }} {{ ansible_hostname }}.{{ ansible_domain }}"
    regexp="^{{ ansible_all_ipv4_addresses }}"
  tags: common