- name: Installeren van de BIND Packages
  yum: pkg={{ item }} state=installed
  with_items:
    - bind-utils
  tags: bind

#################################################################
######################## Blackbox Testen ########################
#################################################################

###

- name: Controleren of poort 53 opstaat op de firewall
  wait_for: port=53 host={{ bind_ip_addr }} delay=3
  tags: bind

###

- name: Test alle NS records die in de variabelen zijn gedefinieerd
  shell: 'dig @{{ bind_ip_addr }} +noall +answer NS {{ bind_zone_name }} | grep -P ".*{{ item }}.*"'
  register: cmd_result
  with_items: bind_zone_name_servers
  tags: bind-test

###

- name: Test alle A records die in de variabelen zijn gedefinieerd
  shell: 'dig @{{ bind_ip_addr }} +noall +answer  {{ item.name }}.{{ bind_zone_name }} | grep {{ item.ip }}'
  register: cmd_result
  with_items: bind_zone_hosts
  tags: bind-test

- name: debug
  debug: var=cmd_result
###

- name: Test alle MX records die in de variabelen zijn gedefinieerd
  shell: 'dig @{{ bind_ip_addr }} +noall +answer {{ bind_zone_name }} MX | grep -P ".*{{ item.preference }}.*{{ item.name }}.{{ bind_zone_name }}"'
  register: cmd_result
  with_items: bind_zone_mail_servers
  tags: bind-test

###

- name: Test de reverse DNS lookup
  shell: 'dig @{{ bind_ip_addr }} +noall +answer -x {{ item.ip }} | grep {{ item.name }}.{{ bind_zone_name }}'
  register: cmd_result
  with_items: bind_zone_hosts
  tags: bind-test

###

- name: Test google.com wanneer recursie is ingesteld
  shell: 'dig @{{ bind_ip_addr }} +noall +answer google.com | grep google.com.'
  register: cmd_result
  when: bind_recursion == "yes"
  tags: bind-test

###

- name: Test google.com wanneer recursie niet ingesteld is, de test moet falen dan.
  shell: 'dig @{{ bind_ip_addr }} +noall +answer google.com | grep google.com.'
  register: cmd_result
  when: bind_recursion == "no"
  ignore_errors: True
  tags: bind-test